<a href="https://colab.research.google.com/github/andreelzs/Linguagens-de-programacao/blob/main/Atividade_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Atividade Prática NumPy — Varejo

## Nível 1: Faturamento Semanal e Filtros

In [1]:
import numpy as np

pecas_vendidas = np.array([150, 120, 90, 210, 300, 250, 180])
pecas_vendidas

array([150, 120,  90, 210, 300, 250, 180])

In [2]:
faturamento = pecas_vendidas * 50
faturamento

array([ 7500,  6000,  4500, 10500, 15000, 12500,  9000])

In [3]:
dias_pico = pecas_vendidas[pecas_vendidas > 200]
dias_pico

array([210, 300, 250])

## Nível 2: Múltiplas Filiais e Falhas de Sistema

In [4]:
vendas = np.array([
    [200, 220, np.nan, 250],
    [150, 180, 160, 190],
    [300, 310, 290, 330]
])
vendas

array([[200., 220.,  nan, 250.],
       [150., 180., 160., 190.],
       [300., 310., 290., 330.]])

In [5]:
total_por_loja = vendas.sum(axis=1)
total_por_loja

array([  nan,  680., 1230.])

In [6]:
media_geral = np.nanmean(vendas)
media_geral

np.float64(234.54545454545453)

In [7]:
meta = np.where(vendas >= 200, 'Meta Atingida', 'Abaixo')
meta

array([['Meta Atingida', 'Meta Atingida', 'Abaixo', 'Meta Atingida'],
       ['Abaixo', 'Abaixo', 'Abaixo', 'Abaixo'],
       ['Meta Atingida', 'Meta Atingida', 'Meta Atingida',
        'Meta Atingida']], dtype='<U13')

## Nível 3: Categorização e Marketing

In [8]:
rng = np.random.default_rng(42)
amostra = rng.choice(['Eletrônicos', 'Roupas', 'Casa'], size=50)
amostra

array(['Eletrônicos', 'Casa', 'Roupas', 'Roupas', 'Roupas', 'Casa',
       'Eletrônicos', 'Casa', 'Eletrônicos', 'Eletrônicos', 'Roupas',
       'Casa', 'Casa', 'Casa', 'Casa', 'Casa', 'Roupas', 'Eletrônicos',
       'Casa', 'Roupas', 'Roupas', 'Roupas', 'Eletrônicos', 'Casa',
       'Casa', 'Roupas', 'Roupas', 'Casa', 'Roupas', 'Roupas', 'Roupas',
       'Eletrônicos', 'Eletrônicos', 'Roupas', 'Casa', 'Eletrônicos',
       'Casa', 'Casa', 'Eletrônicos', 'Roupas', 'Eletrônicos', 'Casa',
       'Casa', 'Roupas', 'Eletrônicos', 'Casa', 'Roupas', 'Casa', 'Casa',
       'Casa'], dtype='<U11')

In [9]:
valores, contagens = np.unique(amostra, return_counts=True)
valores, contagens

(array(['Casa', 'Eletrônicos', 'Roupas'], dtype='<U11'), array([21, 12, 17]))

In [10]:
campanhas = np.array([12000, 45000, 23000, 89000, 31000])
campanha_campea = np.argmax(campanhas)
campanha_campea

np.int64(3)

# Atividade Prática NumPy — Organização e Transformação de Dados

## Nível 1: Sequências e Tipagem

In [11]:
dias_mes = np.arange(1, 31)
dias_mes

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [12]:
metas = np.linspace(20000, 30000, 5)
metas

array([20000., 22500., 25000., 27500., 30000.])

In [13]:
estoque = np.array([10.5, 20.1, 30.9]).astype(int)
estoque

array([10, 20, 30])

In [14]:
ultimos_5 = dias_mes[-5:][::-1]
ultimos_5

array([30, 29, 28, 27, 26])

## Nível 2: Redimensionamento e Proteção de Dados

In [15]:
visitas = np.arange(1, 13)
trimestres = visitas.reshape(4, 3)
trimestres

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [16]:
primeiro_sem = np.arange(1, 7).reshape(1, 6)
segundo_sem = np.arange(7, 13).reshape(1, 6)
ano_completo = np.vstack((primeiro_sem, segundo_sem))
ano_completo

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [17]:
projecao = trimestres[0:1].copy()
projecao

array([[1, 2, 3]])

In [18]:
achatado = trimestres.ravel()
achatado

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## Nível 3: Ranking, Broadcasting e Sistemas Lineares

In [19]:
notas = np.array([85, 92, 78, 95, 88])
ranking = np.argsort(notas)
ranking

array([2, 0, 4, 1, 3])

In [20]:
precos = np.array([100, 200, 300])
precos_coluna = precos[:, np.newaxis]
precos_coluna

array([[100],
       [200],
       [300]])

In [21]:
A = np.array([[2, 1], [1, -1]])
b = np.array([500, 100])
solucao = np.linalg.solve(A, b)
solucao

array([200., 100.])